import carpetBeforeAfter from "../assets/carpet-before-after.jpg";
import carpetExtraction from "../assets/carpet-extraction.jpg";
import commercialFocus from "../assets/commercial-focus.jpg";
import windowCleaning from "../assets/commercial-window-cleaning.jpg";
import detailsCare from "../assets/details-care.jpg";
import floorBeforeAfter from "../assets/floor-before-after.jpg";
import floorCare from "../assets/floor-care.jpg";
import highDusting from "../assets/high-dusting-action.jpg";
import recurringCleaning from "../assets/recurring-cleaning.jpg";
import servicesHero from "../assets/services-hero.jpg";
import socialHero from "../assets/social-sanitation-hero.jpg";
import specializedSanitation from "../assets/specialized-sanitation.jpg";
import stripWaxBeforeAfter from "../assets/strip-wax-before-after.jpg";
import surgicalRoom from "../assets/surgical-room-sanitizing.jpg";
import teamAction from "../assets/team-in-action.jpg";
import tileGroutBeforeAfter from "../assets/tile-grout-before-after.jpg";

export type ServiceContent = {
  slug: string;
  name: string;
  value: string;
  intro: string;
  audience: string;
  scope: string[];
  process: string[];
  benefits: string;
  environments: string[];
  faqs: { question: string; answer: string }[];
  related: string[];
  hero: string;
  detail: string;
  result?: string;
  alt: string;
};

const baseFaqs = (name: string) => [
  { question: `Can ${name.toLowerCase()} be scheduled around business hours?`, answer: "Scheduling is discussed around the facility, access requirements, and scope of work. Contact us to review what works for your operation." },
  { question: "Can this be part of recurring facility service?", answer: "Some needs fit a recurring plan while others are handled as focused projects. We will help determine the practical fit after discussing your property." },
  { question: "How is an estimate prepared?", answer: "We start with the facility, the surfaces or spaces involved, and the result you need, then define a clear scope for the estimate." },
];

const make = (service: Omit<ServiceContent, "faqs"> & { faqs?: ServiceContent["faqs"] }): ServiceContent => ({ ...service, faqs: service.faqs ?? baseFaqs(service.name) });

export const services: ServiceContent[] = [
  make({ slug: "janitorial-services", name: "Janitorial Services", value: "Consistent commercial care that keeps your facility ready for business.", intro: "Janitorial service is the recurring foundation of a professionally maintained building. We coordinate routine cleaning around the spaces people use, the traffic they create, and the standard your business needs to present.", audience: "For offices, shared facilities, commercial properties, and working environments that need dependable ongoing attention.", scope: ["Routine workplace and common-area care", "Restroom and high-touch area attention", "Waste removal and general upkeep", "Schedule-aware facility service"], process: ["Walk the facility", "Define priorities", "Set the schedule", "Perform the work", "Maintain consistency"], benefits: "A reliable janitorial plan protects everyday appearance, supports a cleaner workplace, and keeps small maintenance needs from becoming visible distractions.", environments: ["Corporate offices", "Multi-tenant properties", "Retail facilities", "Commercial workplaces"], related: ["custodial-services", "day-porter-services", "housekeeping-services"], hero: recurringCleaning, detail: socialHero, alt: "Commercial janitorial team maintaining a modern office facility" }),
  make({ slug: "housekeeping-services", name: "Housekeeping Services", value: "Detail-focused upkeep for professional commercial environments.", intro: "Commercial housekeeping supports the day-to-day presentation of interior spaces where comfort, order, and cleanliness shape the experience of staff and visitors.", audience: "For managed facilities, hospitality-adjacent commercial spaces, offices, and properties requiring attentive interior upkeep.", scope: ["Interior presentation and upkeep", "Shared-space cleaning", "Surface and fixture attention", "Detail-focused room care"], process: ["Review spaces", "Prioritize details", "Coordinate access", "Clean methodically", "Complete final review"], benefits: "Professional housekeeping helps spaces feel orderly, cared for, and ready for the people who rely on them.", environments: ["Managed properties", "Office suites", "Common areas", "Commercial interiors"], related: ["janitorial-services", "custodial-services", "first-time-clean"], hero: commercialFocus, detail: detailsCare, alt: "Professional cleaner providing commercial housekeeping in an office" }),
  make({ slug: "custodial-services", name: "Custodial Services", value: "Hands-on facility support built around consistent standards.", intro: "Custodial service keeps essential areas functioning and presentable through practical, recurring attention to the building’s everyday cleaning needs.", audience: "For active facilities that need reliable on-site or scheduled cleaning support across shared and high-use spaces.", scope: ["Common-area maintenance", "Restroom and fixture care", "Routine surface cleaning", "Facility presentation support"], process: ["Assess use patterns", "Set service priorities", "Prepare work areas", "Complete scheduled care", "Review facility condition"], benefits: "Consistent custodial work supports daily operations and gives employees, tenants, and visitors confidence in the facility around them.", environments: ["Commercial buildings", "Shared facilities", "Administrative spaces", "High-use properties"], related: ["janitorial-services", "day-porter-services", "housekeeping-services"], hero: teamAction, detail: recurringCleaning, alt: "Custodial professionals coordinating cleaning inside a commercial building" }),
  make({ slug: "day-porter-services", name: "Day Porter Services", value: "Responsive facility care while your building is active.", intro: "Day porter service provides visible upkeep during operating hours, helping busy commercial spaces respond to changing needs as people move through them.", audience: "For high-traffic properties that benefit from an attentive cleaning presence throughout the business day.", scope: ["Active common-area upkeep", "Touchpoint and entry attention", "Responsive spill and presentation care", "Coordination with facility teams"], process: ["Define daily priorities", "Coordinate operating hours", "Monitor shared spaces", "Respond to needs", "Close out the shift"], benefits: "A day porter helps maintain presentation in real time rather than waiting until the building is empty and the day’s issues have accumulated.", environments: ["Office lobbies", "Retail properties", "Multi-tenant buildings", "Busy common areas"], related: ["janitorial-services", "custodial-services", "window-cleaning"], hero: socialHero, detail: recurringCleaning, alt: "Day porter maintaining a busy modern commercial facility" }),
  make({ slug: "move-in-services", name: "Move-In Services", value: "Prepare your commercial space for the people moving in.", intro: "Move-in cleaning bridges the gap between an empty or recently worked-on space and a workplace that feels ready to occupy.", audience: "For businesses entering offices, commercial suites, and facilities that need focused cleaning before operations begin.", scope: ["Empty-space surface cleaning", "Fixtures and touchpoint attention", "Floor and interior presentation", "Final readiness review"], process: ["Review the space", "Identify priority areas", "Coordinate access", "Complete focused cleaning", "Prepare for occupancy"], benefits: "Professional move-in cleaning gives teams a cleaner starting point and lets the new facility make the right first impression from day one.", environments: ["New office suites", "Relocated businesses", "Commercial tenant spaces", "Prepared facilities"], related: ["first-time-clean", "janitorial-services", "carpet-extraction"], hero: servicesHero, detail: commercialFocus, alt: "Commercial facility being professionally prepared for move-in" }),
  make({ slug: "electrostatic-disinfection", name: "Electrostatic Disinfection", value: "Focused disinfection for high-touch commercial environments.", intro: "Electrostatic disinfection is a specialized application for facilities seeking broader surface coverage as part of a considered sanitation plan.", audience: "For commercial and shared environments where high-touch surfaces and sanitation priorities require focused attention.", scope: ["Space and access preparation", "Focused surface application", "High-touch area attention", "Completion review"], process: ["Discuss the environment", "Define treatment areas", "Prepare the space", "Perform application", "Confirm completion"], benefits: "Professional execution helps ensure the service is planned around the facility rather than treated as a generic spray-and-go task.", environments: ["Medical environments", "Shared workplaces", "High-touch facilities", "Commercial interiors"], related: ["surgical-room-sanitizing-services", "first-time-clean", "janitorial-services"], hero: specializedSanitation, detail: detailsCare, alt: "Specialist performing electrostatic disinfection in a clinical facility" }),
  make({ slug: "surgical-room-sanitizing-services", name: "Surgical Room Sanitizing Services", value: "Methodical sanitation support for demanding clinical spaces.", intro: "Surgical room sanitizing requires careful coordination and disciplined attention to the room, its surfaces, and the facility’s specific expectations.", audience: "For healthcare and clinical environments seeking professional cleaning support for sensitive treatment spaces.", scope: ["Room-specific scope review", "Surface and touchpoint attention", "Methodical cleaning sequence", "Final completion review"], process: ["Coordinate requirements", "Prepare the room", "Work through the defined scope", "Review critical areas", "Confirm completion"], benefits: "A professional approach brings focus, accountability, and careful execution to environments where ordinary facility cleaning is not enough.", environments: ["Surgical rooms", "Clinical facilities", "Treatment spaces", "Healthcare interiors"], related: ["electrostatic-disinfection", "first-time-clean", "custodial-services"], hero: surgicalRoom, detail: specializedSanitation, alt: "Professional sanitizing an empty modern surgical room" }),
  make({ slug: "commercial-carpet-cleaning", name: "Commercial Carpet Cleaning", value: "Refresh high-traffic carpet and restore a cleaner professional appearance.", intro: "Commercial carpet holds the evidence of daily traffic. Professional cleaning targets visible wear and embedded soil across larger working environments.", audience: "For offices, corridors, meeting spaces, and commercial interiors where carpet appearance affects the whole facility.", scope: ["Traffic-area assessment", "Focused spot and soil attention", "Commercial carpet cleaning", "Final appearance review"], process: ["Inspect carpet", "Plan access", "Prepare the area", "Clean methodically", "Review the finish"], benefits: "Professional carpet care improves appearance and supports practical maintenance of a major interior surface.", environments: ["Office corridors", "Meeting spaces", "Commercial suites", "Reception areas"], related: ["carpet-extraction", "janitorial-services", "move-in-services"], hero: carpetBeforeAfter, detail: carpetExtraction, result: carpetBeforeAfter, alt: "Before and after commercial carpet cleaning in an office corridor" }),
  make({ slug: "carpet-extraction", name: "Carpet Extraction", value: "Deep commercial carpet care with a visible, refreshed finish.", intro: "Carpet extraction addresses soil below the surface using professional equipment suited to broad commercial areas and traffic lanes.", audience: "For carpeted workplaces where routine vacuuming no longer delivers the appearance the space needs.", scope: ["Carpet condition review", "Traffic-lane focus", "Professional extraction", "Completion inspection"], process: ["Inspect", "Prepare", "Extract", "Review", "Return the area"], benefits: "Professional extraction can visibly refresh commercial carpet and support a more complete floor-care plan.", environments: ["Corporate offices", "Commercial hallways", "Conference areas", "Multi-tenant facilities"], related: ["commercial-carpet-cleaning", "tile-grout-cleaning", "janitorial-services"], hero: carpetExtraction, detail: carpetBeforeAfter, result: carpetBeforeAfter, alt: "Technician operating commercial carpet extraction equipment" }),
  make({ slug: "tile-grout-cleaning", name: "Tile & Grout Cleaning", value: "Lift the dulling buildup that routine mopping leaves behind.", intro: "Tile can remain presentable while grout lines gradually darken. Focused professional cleaning addresses the full surface and the lines that define it.", audience: "For commercial entrances, restrooms, lobbies, and tiled work areas with visible traffic and buildup.", scope: ["Surface condition review", "Tile and grout-line attention", "Focused professional cleaning", "Finish inspection"], process: ["Inspect surface", "Prepare area", "Work tile and grout", "Clear residue", "Review result"], benefits: "Restored grout contrast and cleaner tile can change the appearance of an entire room without changing the floor itself.", environments: ["Commercial lobbies", "Restrooms", "Food-service spaces", "Tiled corridors"], related: ["acid-wash", "strip-wax", "first-time-clean"], hero: tileGroutBeforeAfter, detail: floorCare, result: tileGroutBeforeAfter, alt: "Before and after commercial tile and grout cleaning" }),
  make({ slug: "strip-wax", name: "Strip & Wax", value: "Restore worn commercial flooring to a cleaner, more polished standard.", intro: "Strip and wax service removes the tired finish that builds up through wear, then restores a more even and professional appearance.", audience: "For resilient commercial floors showing dullness, scuffs, and uneven finish in high-traffic areas.", scope: ["Floor condition review", "Area preparation", "Existing finish removal", "Fresh finish application", "Final appearance review"], process: ["Inspect", "Prepare", "Strip", "Apply finish", "Review"], benefits: "Professional floor restoration improves presentation and supports an intentional maintenance cycle for hard-working commercial surfaces.", environments: ["Institutional corridors", "Commercial offices", "Shared facilities", "High-traffic interiors"], related: ["acid-wash", "tile-grout-cleaning", "first-time-clean"], hero: stripWaxBeforeAfter, detail: floorCare, result: stripWaxBeforeAfter, alt: "Before and after strip and wax floor restoration" }),
  make({ slug: "window-cleaning", name: "Window Cleaning", value: "Clear commercial glass that lets the facility present itself well.", intro: "Commercial window cleaning restores clarity to interior and accessible exterior glass where fingerprints, dust, and environmental buildup interrupt the view.", audience: "For offices, lobbies, storefront-adjacent interiors, and facilities with substantial glass surfaces.", scope: ["Glass-area review", "Frame and edge attention", "Professional glass cleaning", "Clarity and detail check"], process: ["Assess access", "Prepare surroundings", "Clean glass", "Detail edges", "Review clarity"], benefits: "Clean glass supports natural light, a sharper first impression, and the sense that the whole facility is being maintained.", environments: ["Corporate atriums", "Office interiors", "Commercial entrances", "Glass partitions"], related: ["high-dusting", "day-porter-services", "janitorial-services"], hero: windowCleaning, detail: commercialFocus, alt: "Professional cleaning floor-to-ceiling commercial windows" }),
  make({ slug: "high-dusting", name: "High Dusting", value: "Reach the overhead details ordinary cleaning leaves behind.", intro: "High dusting addresses elevated beams, vents, ledges, and structural surfaces where buildup can remain out of sight until it becomes part of the room’s appearance.", audience: "For commercial buildings with atriums, exposed structures, high ceilings, and elevated surfaces outside routine reach.", scope: ["Elevated-area assessment", "Access and surroundings planning", "Overhead dust removal", "Ground-level completion review"], process: ["Survey heights", "Plan access", "Protect the area", "Dust elevated surfaces", "Complete final review"], benefits: "Professional high dusting brings neglected overhead areas back into the facility’s maintenance standard and supports a more complete clean.", environments: ["Commercial atriums", "Industrial-style interiors", "Large lobbies", "High-ceiling facilities"], related: ["window-cleaning", "janitorial-services", "first-time-clean"], hero: highDusting, detail: servicesHero, alt: "Professional performing high dusting in a commercial atrium" }),
  make({ slug: "acid-wash", name: "Acid Wash", value: "Focused restoration for hard commercial surfaces that need more than routine care.", intro: "Acid washing is a specialized cleaning project for appropriate hard surfaces where ordinary maintenance has not addressed visible buildup or staining.", audience: "For commercial properties seeking an evaluated, project-specific response to difficult hard-surface conditions.", scope: ["Surface and condition review", "Project-area preparation", "Focused cleaning work", "Thorough completion review"], process: ["Evaluate surface", "Define scope", "Prepare area", "Perform cleaning", "Inspect finish"], benefits: "Professional planning matters because the surface, condition, surrounding area, and desired result all need to be considered before work begins.", environments: ["Commercial hardscapes", "Facility service areas", "Appropriate tiled surfaces", "Specialty project zones"], related: ["tile-grout-cleaning", "strip-wax", "first-time-clean"], hero: floorCare, detail: tileGroutBeforeAfter, result: tileGroutBeforeAfter, alt: "Professional hard-surface cleaning in a commercial facility" }),
  make({ slug: "first-time-clean", name: "First Time Clean", value: "Establish a professional baseline for ongoing facility care.", intro: "A first-time clean addresses the accumulated details that need attention before a recurring service plan can maintain the right standard.", audience: "For commercial facilities beginning professional service, changing providers, or resetting the condition of key spaces.", scope: ["Whole-facility walkthrough", "Priority and detail identification", "Focused baseline cleaning", "Readiness review for ongoing care"], process: ["Walk the facility", "Define the baseline", "Prioritize buildup", "Complete focused work", "Transition to upkeep"], benefits: "Starting from a considered baseline makes recurring cleaning more consistent and creates shared expectations for the facility going forward.", environments: ["New service accounts", "Occupied offices", "Commercial properties", "Facilities changing providers"], related: ["janitorial-services", "move-in-services", "high-dusting"], hero: detailsCare, detail: teamAction, alt: "Professional cleaner establishing a detailed first clean in a facility" }),
];

export const serviceBySlug = Object.fromEntries(services.map((service) => [service.slug, service])) as Record<string, ServiceContent>;