import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, FileDown, Upload } from "lucide-react";
import { useState, type FormEvent } from "react";

import { SiteFooter, SiteHeader } from "../components/site-chrome";
import { InternalPageHero } from "../components/internal-page-hero";
import careersTeam from "../assets/careers-team.jpg";
import floorImage from "../assets/floor-care.jpg";
import recurringImage from "../assets/recurring-cleaning.jpg";

export const Route = createFileRoute("/careers")({ head: () => ({ meta: [
  { title: "Commercial Cleaning Careers | Social Sanitation" },
  { name: "description", content: "Apply to join Social Sanitation's professional commercial cleaning and facility-services team in Central Florida." },
  { property: "og:title", content: "Build Your Career With Social Sanitation" },
  { property: "og:description", content: "Join a dependable, service-focused commercial cleaning team in Central Florida." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: CareersPage });

const values = [
  { name: "Professionalism", copy: "Take pride in the way you work and represent the team." },
  { name: "Teamwork", copy: "Work alongside people who understand that reliable results are shared results." },
  { name: "Accountability", copy: "Own the details, communicate clearly, and follow through." },
  { name: "Reliability", copy: "Show up prepared and deliver the same standard consistently." },
  { name: "Growth", copy: "Build capability through hands-on commercial cleaning experience." },
];

function CareersPage() { const [submitted, setSubmitted] = useState(false); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
return <div className="overflow-x-hidden bg-background text-foreground"><SiteHeader /><main>
  <InternalPageHero eyebrow="Careers" title="Build Your Career With Social Sanitation" description="Join a professional, service-focused team doing real work for commercial facilities across Central Florida." image={careersTeam} imageAlt="Professional commercial cleaning team working together inside a modern facility" primaryHref="#apply" primaryLabel="Apply Now" />
  <section className="section-space"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-12 lg:px-10"><img src={recurringImage} alt="Commercial janitorial professionals maintaining an office" width={1504} height={1152} loading="lazy" className="aspect-[4/5] w-full object-cover lg:col-span-5" /><div className="lg:col-span-6 lg:col-start-7"><p className="eyebrow mb-6"><span /> Work that matters</p><h2 className="section-title">Dependable people make dependable service possible.</h2><p className="mt-7 leading-8 text-muted-foreground">We value hardworking, detail-oriented people who care about doing the job properly. Social Sanitation offers opportunities within a hands-on commercial cleaning and facility-services operation where consistency, teamwork, and professionalism matter.</p></div></div></section>
  <section className="section-space bg-foreground text-background"><div className="mx-auto max-w-7xl px-5 lg:px-10"><p className="eyebrow eyebrow-light mb-6"><span /> Why work with us</p><h2 className="section-title max-w-3xl">The qualities that build a strong crew.</h2><div className="mt-14 divide-y divide-background/20 border-y border-background/20">{values.map((value, index) => <div key={value.name} className="grid gap-4 py-7 lg:grid-cols-12 lg:items-baseline"><span className="text-xs font-bold text-secondary lg:col-span-1">0{index + 1}</span><h3 className="font-display text-2xl font-semibold lg:col-span-5">{value.name}<span className="text-primary">.</span></h3><p className="leading-7 text-background/65 lg:col-span-6">{value.copy}</p></div>)}</div></div></section>
  <section id="apply" className="scroll-mt-20"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-12"><div className="px-5 py-20 lg:col-span-7 lg:px-10 lg:py-24"><p className="eyebrow mb-6"><span /> Open positions · Apply now</p><h2 className="section-title">Tell us about yourself.</h2><p className="mt-5 max-w-2xl leading-8 text-muted-foreground">Submit your information for current or future commercial cleaning opportunities.</p><form onSubmit={submit} className="mt-10 grid max-w-3xl gap-5 sm:grid-cols-2"><label className="form-label">First name<input required name="firstName" className="form-input" /></label><label className="form-label">Last name<input required name="lastName" className="form-input" /></label><label className="form-label sm:col-span-2">Email<input required type="email" name="email" className="form-input" /></label><label className="form-label sm:col-span-2">Job selection<select required name="job" className="form-input"><option value="">Select an option</option><option>Commercial Cleaning Team</option><option>General Application</option></select></label><label className="form-label sm:col-span-2">Resume<span className="flex min-h-20 items-center justify-center gap-3 border border-dashed border-input bg-surface px-5 text-sm font-semibold normal-case"><Upload className="size-5 text-primary" /> Upload PDF or document<input required type="file" name="resume" accept=".pdf,.doc,.docx" className="sr-only" /></span></label><button type="submit" className="inline-flex min-h-14 items-center justify-center gap-3 bg-primary px-7 text-sm font-extrabold text-primary-foreground sm:col-span-2">Submit Application <ArrowRight className="size-4" /></button>{submitted && <p role="status" className="text-sm font-semibold sm:col-span-2">Thank you. Your application has been noted for this preview.</p>}</form>
          <div className="mt-12 border-t border-border pt-8"><p className="text-xs font-extrabold uppercase tracking-wide text-muted-foreground">Application documents</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><a href="mailto:socialsanitation@gmail.com?subject=New%20Hire%20Application%20Request" className="inline-flex min-h-12 items-center gap-3 border border-border px-5 text-sm font-bold"><FileDown className="size-4 text-primary" /> Request New Hire Application</a><a href="mailto:socialsanitation@gmail.com?subject=Spanish%20Application%20Request" className="inline-flex min-h-12 items-center gap-3 border border-border px-5 text-sm font-bold"><FileDown className="size-4 text-secondary-foreground" /> Solicitar aplicación en español</a></div></div>
        </div><img src={floorImage} alt="Commercial cleaning professional operating floor-care equipment" width={1280} height={960} loading="lazy" className="h-full min-h-[440px] w-full object-cover lg:col-span-5" /></div></section>
  <section className="relative"><img src={careersTeam} alt="Social Sanitation style cleaning team at work" width={1600} height={1056} loading="lazy" className="h-[390px] w-full object-cover" /><div className="absolute inset-0 bg-foreground/75" /><div className="absolute inset-0 grid place-items-center px-5 text-center text-background"><div><h2 className="font-display text-2xl font-semibold sm:text-3xl">Good work starts with good people.</h2><p className="mt-5 text-background/70">Bring your reliability, attention to detail, and willingness to work as a team.</p><a href="#apply" className="mt-8 inline-flex min-h-14 items-center bg-primary px-7 text-sm font-extrabold text-primary-foreground">Apply to Join the Team</a></div></div></section>
</main><SiteFooter /></div>; }