import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Phone } from "lucide-react";

import { CentralFloridaMap } from "../components/central-florida-map";
import { ArrowLink, SiteFooter, SiteHeader } from "../components/site-chrome";
import { InternalPageHero } from "../components/internal-page-hero";
import regionalHero from "../assets/central-florida-commercial.jpg";
import commercialImage from "../assets/commercial-focus.jpg";
import recurringImage from "../assets/recurring-cleaning.jpg";
import teamImage from "../assets/team-in-action.jpg";

export const Route = createFileRoute("/service-areas")({ head: () => ({ meta: [
  { title: "Central Florida Service Area | Social Sanitation" },
  { name: "description", content: "Commercial cleaning across Hillsborough, Pinellas, Polk, and Pasco counties in Central Florida." },
  { property: "og:title", content: "Commercial Cleaning Across Central Florida" },
  { property: "og:description", content: "Professional commercial cleaning and sanitation across Social Sanitation's Central Florida service area." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: ServiceAreasPage });

function ServiceAreasPage() { return <div className="overflow-x-hidden bg-background text-foreground"><SiteHeader /><main>
  <InternalPageHero eyebrow="Service Areas" title="Commercial Cleaning Across Central Florida" description="Professional cleaning and sanitation for businesses and facilities throughout our established service area." image={regionalHero} imageAlt="Central Florida commercial landscape and business facilities" />
  <section className="section-space"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-12 lg:px-10"><div className="lg:col-span-5"><p className="eyebrow mb-6"><span /> Central Florida coverage</p><h2 className="section-title">Local service for working commercial spaces.</h2><p className="mt-7 leading-8 text-muted-foreground">Social Sanitation supports commercial properties across our Central Florida footprint with dependable recurring care and focused specialty work. We understand that location, access, operating hours, and facility requirements all shape the right cleaning plan.</p></div><img src={recurringImage} alt="Professional janitorial team working inside a commercial facility" width={1504} height={1152} loading="lazy" className="aspect-[5/4] w-full object-cover lg:col-span-6 lg:col-start-7" /></div></section>
  <section className="section-space bg-foreground text-background"><div className="mx-auto grid max-w-[1440px] items-center gap-12 px-5 lg:grid-cols-12 lg:px-10"><div className="lg:col-span-8"><CentralFloridaMap /></div><div className="lg:col-span-4"><p className="eyebrow eyebrow-light mb-6"><span /> Service footprint</p><h2 className="font-display text-3xl font-semibold leading-tight">Four counties.<br />One standard.</h2><div className="my-8 divide-y divide-background/20 border-y border-background/20">{["Hillsborough County", "Pinellas County", "Polk County", "Pasco County"].map((county) => <div key={county} className="py-4 font-bold">{county}</div>)}</div><p className="text-sm leading-7 text-background/65">Service availability can vary by location, schedule, facility type, and cleaning requirements. Contact us to confirm coverage for your property.</p></div></div></section>
  <section className="section-space"><div className="mx-auto grid max-w-[1440px] items-stretch gap-0 px-5 lg:grid-cols-12 lg:px-10"><img src={commercialImage} alt="Professional cleaner maintaining a modern commercial office" width={1536} height={1024} loading="lazy" className="h-full min-h-[360px] w-full object-cover lg:col-span-7" /><div className="flex items-center bg-brand-wash p-8 lg:col-span-5 lg:p-12"><div><p className="eyebrow mb-6"><span /> Commercial properties we serve</p><h2 className="section-title">Built around how your facility works.</h2><p className="mt-7 leading-8 text-muted-foreground">We support businesses and facilities with recurring janitorial services, custodial work, floor care, carpet cleaning, sanitation, day porter services, and specialized cleaning.</p><div className="mt-8"><ArrowLink href="/services">Explore Services</ArrowLink></div></div></div></div></section>
  <section className="relative"><img src={teamImage} alt="Commercial cleaning team working in a Central Florida facility" width={1536} height={1024} loading="lazy" className="h-[460px] w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-foreground/90 via-foreground/60 to-transparent" /><div className="absolute inset-0 mx-auto flex max-w-[1440px] items-center px-5 text-background lg:px-10"><div className="max-w-xl"><p className="eyebrow eyebrow-light mb-6"><span /> In our service area?</p><h2 className="font-display text-2xl font-semibold sm:text-3xl">Let’s walk your facility and define the right plan.</h2><p className="mt-6 leading-8 text-background/75">Tell us where your property is and what kind of commercial cleaning support you need.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/contact#estimate" className="inline-flex min-h-14 items-center justify-center gap-3 bg-primary px-7 text-sm font-extrabold text-primary-foreground">Request a Free Estimate <ArrowRight className="size-4" /></a><a href="tel:+18136972664" className="inline-flex min-h-14 items-center justify-center gap-3 border border-background/50 px-7 text-sm font-bold"><Phone className="size-4" /> (813) 697-2664</a></div></div></div></section>
</main><SiteFooter /></div>; }