import { createFileRoute } from "@tanstack/react-router";
import { Pause, Phone, Play, X } from "lucide-react";
import { useState } from "react";

import { ArrowLink, SiteFooter, SiteHeader } from "../components/site-chrome";
import { InternalPageHero } from "../components/internal-page-hero";
import carpetImage from "../assets/carpet-extraction.jpg";
import floorProof from "../assets/floor-before-after.jpg";
import floorImage from "../assets/floor-care.jpg";
import highDusting from "../assets/high-dusting-action.jpg";
import recurringImage from "../assets/recurring-cleaning.jpg";
import servicesHero from "../assets/services-hero.jpg";
import teamImage from "../assets/careers-team.jpg";
import tileImage from "../assets/tile-grout-before-after.jpg";

export const Route = createFileRoute("/videos")({ head: () => ({ meta: [
  { title: "Commercial Cleaning Videos | Social Sanitation" },
  { name: "description", content: "Watch Social Sanitation perform day porter, high dusting, carpet extraction, strip and wax, and acid wash services." },
  { property: "og:title", content: "Cleaning in Action | Social Sanitation" },
  { property: "og:description", content: "A behind-the-scenes look at professional commercial cleaning work." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: VideosPage });

function VideosPage() { const [active, setActive] = useState<string | null>(null); return <div className="overflow-x-hidden bg-background text-foreground"><SiteHeader /><main>
  <InternalPageHero eyebrow="Videos" title="Cleaning in Action" description="See our team perform real commercial cleaning, restoration, and facility-maintenance work." image={servicesHero} imageAlt="Professional cleaner actively operating equipment in a large commercial facility" />
  <section className="section-space"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="grid gap-7 lg:grid-cols-2 lg:items-end"><div><p className="eyebrow mb-6"><span /> The collection</p><h2 className="section-title">A closer look at how the work gets done.</h2></div><p className="max-w-xl leading-8 text-muted-foreground lg:justify-self-end">Professional equipment, practiced technique, and people who understand the details behind a reliable result.</p></div><div className="mt-14 grid gap-6 lg:grid-cols-12"><Preview image={recurringImage} title="Day Porter Services" className="min-h-[360px] lg:col-span-8" onPlay={setActive} /><Preview image={highDusting} title="High Dusting" className="min-h-[360px] lg:col-span-4" onPlay={setActive} /><Preview image={carpetImage} title="Carpet Extraction" className="min-h-[360px] lg:col-span-5" onPlay={setActive} /><Preview image={floorImage} title="Strip & Wax" className="min-h-[360px] lg:col-span-7" onPlay={setActive} /><Preview image={tileImage} title="Acid Wash" className="min-h-[430px] lg:col-span-12" onPlay={setActive} /></div></div></section>
  <section className="bg-foreground text-background"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-12"><img src={floorImage} alt="Commercial floor-cleaning equipment in active use" width={1280} height={960} loading="lazy" className="h-full min-h-[430px] w-full object-cover lg:col-span-7" /><div className="flex items-center px-5 py-20 lg:col-span-5 lg:px-12"><div><p className="eyebrow eyebrow-light mb-6"><span /> The work behind the result</p><h2 className="section-title">Equipment is only part of the equation.</h2><p className="mt-7 leading-8 text-background/70">Professional results come from choosing the proper equipment, applying the right technique, working consistently, and paying attention to the details that change the final result.</p></div></div></div></section>
  <section className="section-space"><div className="mx-auto grid max-w-[1440px] items-center gap-12 px-5 lg:grid-cols-12 lg:px-10"><div className="lg:col-span-4"><p className="eyebrow mb-6"><span /> Results in context</p><h2 className="section-title">Watch the process. See the finish.</h2><p className="mt-7 leading-8 text-muted-foreground">The action leads to the proof: cleaner carpet, restored floors, and surfaces brought back to a professional standard.</p><div className="mt-8"><ArrowLink href="/work">View Our Work</ArrowLink></div></div><img src={floorProof} alt="Before and after commercial floor restoration" width={1536} height={1024} loading="lazy" className="aspect-[16/10] w-full object-cover lg:col-span-7 lg:col-start-6" /></div></section>
  <section className="relative"><img src={teamImage} alt="Commercial cleaning team working together inside a facility" width={1600} height={1056} loading="lazy" className="h-[420px] w-full object-cover" /><div className="absolute inset-0 bg-foreground/75" /><div className="absolute inset-0 grid place-items-center px-5 text-center text-background"><div><h2 className="font-display text-2xl font-semibold sm:text-3xl">Bring this standard to your facility.</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="/contact#estimate" className="inline-flex min-h-14 items-center justify-center bg-primary px-7 text-sm font-extrabold text-primary-foreground">Request a Free Estimate</a><a href="tel:+18136972664" className="inline-flex min-h-14 items-center justify-center gap-2 border border-background/50 px-7 text-sm font-bold"><Phone className="size-4" /> (813) 697-2664</a></div></div></div></section>
  </main><SiteFooter />{active && <div role="dialog" aria-modal="true" className="fixed inset-0 z-[70] grid place-items-center bg-foreground/95 p-5" onClick={() => setActive(null)}><div className="relative w-full max-w-4xl bg-background p-8 text-center" onClick={(event) => event.stopPropagation()}><Pause className="mx-auto size-9 text-primary" /><h2 className="mt-5 font-display text-2xl font-semibold">{active}</h2><p className="mt-3 text-muted-foreground">Video preview ready for the original Social Sanitation footage.</p><button type="button" onClick={() => setActive(null)} aria-label="Close preview" className="absolute right-3 top-3 grid size-10 place-items-center border border-border"><X /></button></div></div>}</div>; }

function Preview({ image, title, className, onPlay }: { image: string; title: string; className: string; onPlay: (value: string) => void }) { return <figure className={`group relative overflow-hidden ${className}`}><img src={image} alt={`${title} professional cleaning preview`} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.02]" /><div className="absolute inset-0 bg-video-overlay" /><button type="button" onClick={() => onPlay(title)} aria-label={`Play ${title} preview`} className="absolute left-1/2 top-1/2 grid size-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-primary text-primary-foreground"><Play className="ml-1 size-6 fill-current" /></button><figcaption className="absolute bottom-0 left-0 p-7 font-display text-xl font-semibold text-background">{title}</figcaption></figure>; }