import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Phone } from "lucide-react";
import { useState } from "react";

import type { ServiceContent } from "../lib/service-content";
import { serviceBySlug } from "../lib/service-content";
import { SiteFooter, SiteHeader } from "./site-chrome";
import { InternalPageHero } from "./internal-page-hero";

export function ServicePageTemplate({ service }: { service: ServiceContent }) {
  const [position, setPosition] = useState(50);
  return <div className="overflow-x-hidden bg-background text-foreground"><SiteHeader /><main>
    <InternalPageHero eyebrow="Services" title={service.name} description={service.value} image={service.hero} imageAlt={service.alt} />

    <section className="section-space"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-12 lg:px-10"><img src={service.detail} alt={`${service.name} professional commercial cleaning detail`} loading="lazy" className="aspect-[4/5] w-full object-cover lg:col-span-5" /><div className="lg:col-span-6 lg:col-start-7"><p className="eyebrow mb-6"><span /> About the service</p><h2 className="section-title">The right care for the work at hand.</h2><p className="mt-7 leading-8 text-muted-foreground">{service.intro}</p><p className="mt-5 leading-8 text-muted-foreground">{service.audience}</p></div></div></section>

    <section className="section-space bg-surface"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 lg:grid-cols-12 lg:px-10"><div className="lg:col-span-5"><p className="eyebrow mb-6"><span /> What we do</p><h2 className="section-title">A defined scope. A professional finish.</h2><p className="mt-7 leading-8 text-muted-foreground">We shape the work around the facility and the condition of the space, keeping the service focused on what genuinely needs attention.</p></div><div className="divide-y divide-border border-y border-border lg:col-span-6 lg:col-start-7">{service.scope.map((item, index) => <div key={item} className="flex items-center gap-5 py-6"><span className="text-xs font-bold text-muted-foreground">0{index + 1}</span><p className="font-display text-lg font-semibold">{item}</p><Check className="ml-auto size-5 text-primary" /></div>)}</div></div></section>

    <section className="section-space"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><p className="eyebrow mb-6"><span /> Our process</p><h2 className="section-title max-w-2xl">Clear steps from preparation to completion.</h2><div className="mt-12 grid border-y border-border sm:grid-cols-5">{service.process.map((step, index) => <div key={step} className="relative border-b border-border px-5 py-7 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><span className="text-xs font-bold text-primary">0{index + 1}</span><p className="mt-4 font-display text-base font-semibold leading-snug">{step}</p></div>)}</div></div></section>

    <section className="bg-foreground text-background"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-12"><div className="flex items-center px-5 py-16 lg:col-span-5 lg:px-10 lg:py-20"><div><p className="eyebrow eyebrow-light mb-6"><span /> Why professional cleaning matters</p><h2 className="section-title">The result is more than surface level.</h2><p className="mt-7 leading-8 text-background/70">{service.benefits}</p></div></div><img src={service.hero} alt={`${service.name} performed in a commercial environment`} loading="lazy" className="h-full min-h-[430px] w-full object-cover lg:col-span-7" /></div></section>

    {service.result && <section className="section-space"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="mb-10"><p className="eyebrow mb-6"><span /> Before &amp; after</p><h2 className="section-title">See what focused work can change.</h2><p className="mt-5 max-w-xl leading-8 text-muted-foreground">Use the slider to explore this visual example. Project conditions and results vary by surface and facility.</p></div><div className="relative aspect-[4/3] overflow-hidden sm:aspect-[16/9] lg:aspect-[2/1]"><div className="absolute inset-0 bg-cover bg-left" style={{ backgroundImage: `url(${service.result})`, backgroundSize: "200% 100%" }} /><div className="absolute inset-0 bg-cover bg-right" style={{ backgroundImage: `url(${service.result})`, backgroundSize: "200% 100%", clipPath: `inset(0 0 0 ${position}%)` }} /><div className="pointer-events-none absolute inset-y-0 w-px bg-background" style={{ left: `${position}%` }}><span className="absolute left-1/2 top-1/2 grid size-12 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-background shadow-editorial">↔</span></div><span className="absolute left-5 top-5 bg-foreground px-4 py-2 text-xs font-bold uppercase text-background">Before</span><span className="absolute right-5 top-5 bg-primary px-4 py-2 text-xs font-bold uppercase text-primary-foreground">After</span><input aria-label={`Compare before and after ${service.name}`} type="range" min="15" max="85" value={position} onChange={(event) => setPosition(Number(event.target.value))} className="absolute inset-0 h-full w-full cursor-ew-resize opacity-0" /></div></div></section>}

    <section className="section-space bg-brand-wash"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-12 lg:px-10"><div className="lg:col-span-5"><p className="eyebrow mb-6"><span /> Who we serve</p><h2 className="section-title">Commercial environments with real operating demands.</h2></div><div className="divide-y divide-border border-y border-border lg:col-span-6 lg:col-start-7">{service.environments.map((environment) => <p key={environment} className="py-5 font-display text-xl font-semibold">{environment}</p>)}</div></div></section>

    <section className="section-space"><div className="mx-auto max-w-5xl px-5 lg:px-10"><p className="eyebrow mb-6"><span /> Frequently asked questions</p><h2 className="section-title">Planning your {service.name.toLowerCase()}.</h2><div className="mt-10 divide-y divide-border border-y border-border">{service.faqs.map((faq) => <details key={faq.question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-display text-lg font-semibold"><span>{faq.question}</span><span className="text-primary group-open:rotate-45">+</span></summary><p className="mt-4 max-w-3xl leading-8 text-muted-foreground">{faq.answer}</p></details>)}</div></div></section>

    <section className="border-y border-border bg-surface py-16"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><p className="text-xs font-extrabold uppercase tracking-wide text-muted-foreground">Related services</p><div className="mt-6 grid sm:grid-cols-3">{service.related.map((slug) => { const related = serviceBySlug[slug]; if (!related) return null; return <Link key={slug} to="/services/$service" params={{ service: slug }} className="group flex items-center justify-between border-t border-border py-5 font-display font-semibold sm:mr-8"><span>{related.name}</span><ArrowRight className="size-4 text-primary transition-transform group-hover:translate-x-1" /></Link>; })}</div></div></section>

    <section className="relative"><img src={service.detail} alt={`${service.name} commercial cleaning service`} loading="lazy" className="h-[420px] w-full object-cover" /><div className="absolute inset-0 bg-foreground/78" /><div className="absolute inset-0 grid place-items-center px-5 text-center text-background"><div className="max-w-3xl"><p className="eyebrow eyebrow-light mb-6 justify-center"><span /> Discuss your requirement</p><h2 className="font-display text-2xl font-semibold leading-tight sm:text-3xl">Bring a professional standard to your {service.name.toLowerCase()}.</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="/contact#estimate" className="inline-flex min-h-14 items-center justify-center gap-3 bg-primary px-7 text-sm font-extrabold text-primary-foreground">Request a Free Estimate <ArrowRight className="size-4" /></a><a href="tel:+18136972664" className="inline-flex min-h-14 items-center justify-center gap-3 border border-background/50 px-7 text-sm font-bold text-background"><Phone className="size-4" /> (813) 697-2664</a></div></div></div></section>
  </main><SiteFooter /></div>;
}